### ISSUE TITLE
Lighthouse Report

### ISSUE THREAD

**Issue by andrewlew1s** [holistic-web/toolbox#119]
<details>
<summary>
I ran google lighthouse and it looks like we have one area where we really need to improve:

Performance.

In terms of everything else, we seem to be pretty good. Maybe we could try to boost SEO into the 90s.</summary>
<p>
To run lighthouse, just inspect the page in Chrome and go to the audits panel. Screenshots are reports for performance only. In the screenshots also it says to try running in incognito, I did that and we got an even worse performance score of literally 1/100.

![Screen Shot 2020-03-23 at 2 29 57 PM](https://user-images.githubusercontent.com/39633492/77365207-ebbb9700-6d12-11ea-9661-0fbbee495ff5.png)
![Screen Shot 2020-03-23 at 2 30 10 PM](https://user-images.githubusercontent.com/39633492/77365208-ec542d80-6d12-11ea-832b-62429824b060.png)
![Screen Shot 2020-03-23 at 2 30 24 PM](https://user-images.githubusercontent.com/39633492/77365210-ec542d80-6d12-11ea-8dc5-94f8ab7fa8de.png)

</p>
</details>

## Actions
- [ ] make site mobile friendly
- [ ] improve images

**Comment by michaelfitzhavey** [comment]
Looks like a great initial action from this issue would be to find out how to improve our `performance` and `SEO` scores.

Once we're wrapping that up we should add a plan to regularly audit our sites with lighthouse, perhaps once a month and perhaps [automatically](https://www.npmjs.com/package/lighthouse)?

**Comment by andrewlew1s** [comment]
Automatic checking would be useful, but probably worth considering opportunity cost of spending too much time on seeing as it only takes three clicks to run it manually.

**Comment by michaelfitzhavey** [comment]
But how often will we remember to run manually 🤔. The benefits of automating these checks would be that we will see the effect each code change has on the scores of our product.

I agree with you it isn't a quick win though. I've added this idea to the roadmap. For now we should focus on some key tasks and add them to the top comment of this issue. I'll get a few ideas in there now.
