### ISSUE TITLE
Analytics Improvements

### ISSUE THREAD

**Issue by michaelfitzhavey** [holistic-web/toolbox#23]
We now have analytics set up 🎈 however there is more to be done 👷 .

This is a useful link to Analytics Events:
https://console.firebase.google.com/u/0/project/holistic-toolbox/analytics/app/web:OTBjZmUzYjEtNGI1Yi00MDE0LWFhZTItN2EyZmQ1ZDVkMGZk/events~2Freport~2Fpage_view%3Ft=1581205323925&fpn=94330098957&swu=1&sgu=1&sus=upgraded&params=_u..pageSize%253D25%2526_r..eventId%253Dpage_view&cs=app.m.events.detail&r=page_view&g=1

We want our analytics to:
- [x] tell us which url they have visited
- [x] how many times an event on that url has occured, for instance 'format'
- [x] document how we can find this information in the Readme
- [ ] have better naming

**Comment by andrewlew1s** [comment]
I did some research this evening on this. FIrebase automatically logs some events, one of which is page-view. If you click on it, it actually tells you which subdomains have been viewed and the percentage. 
![analytics](https://user-images.githubusercontent.com/39633492/73820469-b8469c80-47a6-11ea-9252-34dad9d58242.JPG)

I also looked into adding custom events, and it seems a little confusing as to how to set the parameters correctly for the log event method: 

https://firebase.google.com/docs/reference/js/firebase.analytics.Analytics.html#logevent

**Comment by michaelfitzhavey** [comment]
Thats great news re: seeing which site is used more. Perhaps we should add a document to processes saying how to get analytics information we might want.

Regarding logging custom events (such as `json-formatted`) the logEvent method looks like it should work great. I don't think we need to add any custom parameters by default, we don't need to store the JSON they are converting or anything like that.

**Comment by andrewlew1s** [comment]
Experiments going on in #63 , will have to come back and check if some events have fired as they do not show up immediately on the console.

**Comment by andrewlew1s** [comment]
Following this tutorial and using google tag manager should accomplish our goals:
https://www.youtube.com/watch?v=WPEdkc_feNM

**Comment by michaelfitzhavey** [comment]
Let's get a link to the GTM console into the readme and discuss setting up events to finish this task off. This issue has been open for over a month! 😱

**Comment by andrewlew1s** [comment]
This is a quick tutorial for setting up GTM:

Install this chrome extension:
https://chrome.google.com/webstore/detail/tag-assistant-by-google/kejbdjndbnbjgmefkgdddjlbokphdefk?hl=en

Check out feat/analytics-branch #63 

Run local host of site trying to add events to

Run chrome extension on local site

**Comment by andrewlew1s** [comment]
> Let's get a link to the GTM console into the readme and discuss setting up events to finish this task off. This issue has been open for over a month! 😱

Eek! I think we are nearly there though. As seen below Tag Manager seems to be happy with our event trigger and tag, but I can't find it on analytics? 

![Screen Shot 2020-02-24 at 2 35 27 PM](https://user-images.githubusercontent.com/39633492/75197918-3813b700-5714-11ea-8082-f38d8f557a31.png)

**Comment by andrewlew1s** [comment]
It is now possible to find the corresponding event in the analytics console under:
Behaviour -> Events

**Comment by andrewlew1s** [comment]
Should we close this for now?

**Comment by michaelfitzhavey** [comment]
Some ideas I have around the analytics doc: https://github.com/holistic-web/toolbox/pull/96

**Comment by andrewlew1s** [comment]
Events seem to be tracking well @michaelfitzhavey :

![Screen Shot 2020-03-16 at 12 13 53 AM](https://user-images.githubusercontent.com/39633492/76731628-19a14a00-671b-11ea-955e-04902df03188.png)

**Comment by michaelfitzhavey** [comment]
@andrewlew1s what work is remaining on this issue?

**Comment by andrewlew1s** [comment]
@michaelfitzhavey none as far as I can tell, so I'm going to close the issue. Events are tracked, and there is good documentation.

**Comment by andrewlew1s** [comment]
feel free to reopen if needed

**Comment by michaelfitzhavey** [comment]
> Events are tracked, and there is good documentation.

Music to my ears - nice one!
