### ISSUE TITLE
Number Converter Improvements

### ISSUE THREAD

**Issue by andrewlew1s** [holistic-web/toolbox#56]
We should improve Number Converter in the following ways:

- [x] Add *to* decimal options
- [x] Pick n Mix to and from
- [x] Automatically add 0o and 0x (and capitalise) when "to octal/hex" selected

**Comment by andrewlew1s** [comment]
> This issue seems to be stale

But not for long! Tested some UI options yesterday night, I think a card surrounding the values that also had more options kind of like this:

https://www.rapidtables.com/convert/number/index.html

**Comment by michaelfitzhavey** [comment]
@andrewlew1s not sure duplicating the input multiple times will make for a simpler UX / [DX](https://hackernoon.com/developer-experience-dx-devs-are-people-too-6590d6577afe).

Also I think following our convention where buttons go in the action bar for now at least might be a good idea.

Thoughts?

**Comment by andrewlew1s** [comment]
> @andrewlew1s I'm not sure duplicating the input multiple times will make for a simpler UX / [DX](https://hackernoon.com/developer-experience-dx-devs-are-people-too-6590d6577afe).
> 
> Also I think following our convention where buttons go in the action bar for now at least might be a good idea.
> 
> Thoughts?

I meant to reply to this earlier saying I agree with the philosophy. Keeping it the same is better.

**Comment by andrewlew1s** [comment]
This is ready for review

**Comment by andrewlew1s** [comment]
Deployed and tested!
