### ISSUE TITLE
Investigate Google Tag Manger

### ISSUE THREAD

**Issue by andrewlew1s** [holistic-web/toolbox#62]
GTM will hopefully enable is to add analytics and ads more easily. This may help with #23 .

What is GTM?
*Use Google Tag Manager to manage tags (such as measurement and marketing optimization JavaScript tags) on your site. Without editing your site code, you use GTM user interface to add and update Google Ads, Google Analytics, Floodlight, and non-Google tags. This reduces errors and allows you to to deploy tags on your site quickly.*

Quick Start:
https://developers.google.com/tag-manager/quickstart

**Comment by andrewlew1s** [comment]
> This issue seems to be stale

This is now a priority

**Comment by andrewlew1s** [comment]
https://www.youtube.com/watch?v=WPEdkc_feNM

**Comment by andrewlew1s** [comment]
Google Tag Manager has now been investigated. We have decided to use it going forward in #63

**Comment by michaelfitzhavey** [comment]
@andrewlew1s #23 seems to be a pull request not an issue. What changes do we plan to make to the project in #23?

**Comment by andrewlew1s** [comment]
> @andrewlew1s #63 appears to be a pull request, not an issue. What changes do we plan to make to the project in #63?

Thanks for pointing this out, I have updated this.

> I'd also like to write a short description of what we found from our investigation before we close this issue. _I.e. I'd like to know what it can do for us and how to do it, I'm not sure a link to a youtube video in this issue achieves that._

Thanks for the review. The youtube link was more for safe keeping, rather than an explanation of the issue. 

In terms of what we discovered from this investigation, we have found that our work in #63 up to this point could have been accomplished more simply by using Google Tag Manager. Instead of programmatically adding in custom analytics events to each page we can use GTM to add them via a console. This proved mildly more challenging than expected so I didn't complete the task in one sitting and hope to finish it soon in #23

**Comment by andrewlew1s** [comment]
This is a quick tutorial for setting up GTM:

Install this chrome extension:
https://chrome.google.com/webstore/detail/tag-assistant-by-google/kejbdjndbnbjgmefkgdddjlbokphdefk?hl=en

Check out feat/analytics-branch #63 

Run local host of site trying to add events to

Run chrome extension on local site

**Comment by andrewlew1s** [comment]
We should soon be able to close this issue as we now have event analytics being passed through GTM and visible in the analytics console

**Comment by andrewlew1s** [comment]
At last! 🗻
