### ISSUE TITLE
NLP Toolkit

### ISSUE THREAD

**Issue by michaelfitzhavey** [holistic-web/toolbox#69]
It looks like we can make a pretty neat topic tagging tool using the npm package [compromise](npm compromise).

For a simple tool, how about one that takes in text and returns a list of topics? I'm sure there are better ideas out there but this still sounds pretty sweet.

**Comment by dan47bennett** [comment]
This has begun as a general NLP tool in #70.

**Comment by dan47bennett** [comment]
NLP toolkit completed and added to the toolbox.
