### ISSUE TITLE
JS Formatter

### ISSUE THREAD

**Issue by Charlielancaster** [holistic-web/toolbox#73]
Much like how we can format JSON, we can do some basic JavaScript formatting too. Starting with unminifiying(?) and then moving on to linting 

- [x] Minify JavaScript
- [x] Unminify JavaScript

**Comment by Charlielancaster** [comment]
Seems that minification is that same for all file types (html, css, js, etc) and should just be a separate tool

found a nice video here of how to do it in vue - https://www.youtube.com/watch?v=_-p5gYWHZNg

**Comment by michaelfitzhavey** [comment]
@Charlielancaster true minification should be the same for all files, but as we have the feature baked into [json-formatter](http://json-formatter.holistic-toolbox.com) by selecting no spacing it would be nice to have that feature baked in here maybe

**Comment by andrewlew1s** [comment]
@michaelfitzhavey I'm not sure the automation put this in the right place!

**Comment by Charlielancaster** [comment]
Reopening issue to finish the work!

**Comment by Charlielancaster** [comment]
This is ready for review in #93

**Comment by Charlielancaster** [comment]
Closing as change is live
