### ISSUE TITLE
Add storybook as a way to demo and debug toolbox-layout

### ISSUE THREAD

**Issue by michaelfitzhavey** [holistic-web/toolbox#75]
[Storybook](https://storybook.js.org/docs/guides/guide-vue/) is a neat way explain how our components work and also to ensure we haven't had any unintended side effects when we make changes.

We should use it to demo our layout package.

**Comment by michaelfitzhavey** [comment]
This is in progress in #76

**Comment by Charlielancaster** [comment]
Why don't we turn this into a toolbox-style guide? We can use it to show some documentation and design patterns? Much like how Audi have, here https://www.audi.com/ci/en/intro/brand-appearance.html

The reason for me suggesting this, is to eventually evolve this into a Holistic brand guide for our external Designers, Developers or even potential clients that may happen across our site/we use to show as an example of our work

**Comment by michaelfitzhavey** [comment]
This sounds useful, however at the point we're making a style guide it may be simpler to make that as a static website.

It sounds like a good idea that would help us, but I'm not exactly sure how to do it at the moment! :smil

**Comment by michaelfitzhavey** [comment]
#76 is merged and deployed
