### ISSUE TITLE
Base 64 Encoder

### ISSUE THREAD

**Issue by andrewlew1s** [holistic-web/toolbox#91]
I want to make a new tool to encode images in Base64!

**Why?**
Base64 encoded images can be embedded using img tags or CSS, speeding up load times for smaller images by preventing additional HTTP requests. This can be done to build single-file mockups / demo pages for your clients, HTML email signatures that will not trigger the nasty "show images" warning in email clients, etc._

Also they are used in sending images to to certain APIs

Here is a stack-overflow on how to do it in js:
https://stackoverflow.com/questions/6150289/how-to-convert-image-into-base64-string-using-javascript

Here is an example site:
https://www.base64-image.de/

**Comment by michaelfitzhavey** [comment]
This sounds cool, let's make it two way (image to base64 and vice versa)? I'm super down to help out on this one 🔢

**Comment by andrewlew1s** [comment]
We should start this soon!

**Comment by michaelfitzhavey** [comment]
As #113 is still in progress I think should we close this and move the idea to the roadmap? Unless there is any plan to build this tool in the next couple of days.

**Comment by andrewlew1s** [comment]
sounds good to reopen later

**Comment by michaelfitzhavey** [comment]
@andrewlew1s if we are closing this issue we should re add this idea to:
https://github.com/holistic-web/toolbox/blob/master/.project/tool-ideas.md

**Comment by andrewlew1s** [comment]
done
