### ISSUE TITLE
Toolbox Improvements

### ISSUE THREAD

**Issue by andrewlew1s** [holistic-web/toolbox#92]
We discussed how it is now important that we improve the overall layout for our website and tools.

Some ideas to be implemented are:

## Plan

- [x] remove the main picture, it doesn't add anything
    _PR ready https://github.com/holistic-web/toolbox/pull/97_

- [x] add a little more text about what the toolbox is
   _PR ready_ #103

- [x] add tags to tools
    _PR ready https://github.com/holistic-web/toolbox/pull/102_

- add floating ninja to the header
    - [x] add feature to layout library
        _PR ready https://github.com/holistic-web/toolbox/pull/104_
    - [x] roll out to website and all tools
        _PR ready https://github.com/holistic-web/toolbox/pull/108_

- [ ] allow tools to be filtered by name or tag
    _PR in progress #114_

- [ ] clicking on a tag should trigger filtering by that tag

- [ ] add consistency to tool picture and button sizes
    _PR in progress #116_

- [ ] add a contact us form, or perhaps just an email address, to report bugs or suggest changes
    _PR in progress #118_ 

- [ ] make the site mobile friendly

- [ ] audit the page with google lighthouse and make any suggested changes

- [ ] website should correctly use tabindex and be able to iterate through links

- swap the location of the `Holistic Toolbox` branding and the Home button.
    - [x] update layout package to look like this
        _PR ready #98_
    - [x] use latest version of layout package
        _PR ready #100_

- fix colour when rendering code in ToolMarkdown
    - [x] make the fix
        _PR ready https://github.com/holistic-web/toolbox/pull/105_
    - [x] deploy to all tools
        _PR ready https://github.com/holistic-web/toolbox/pull/108_

## Polish

- [ ] add default from and to values for Number Converter
    _PR ready #117_ 

- [x] tools should scroll to top of page on error
    _PR ready https://github.com/holistic-web/toolbox/pull/110_

- [x] fix scroll issue whenever taskbar is present
    _PR ready https://github.com/holistic-web/toolbox/pull/106_

- resolve marked console error
    - [x] make fix
        _PR ready https://github.com/holistic-web/toolbox/pull/107_
    - [x] roll out new layout to all tools
        _PR ready https://github.com/holistic-web/toolbox/pull/108_

- [ ] fix bug in json browser where JSON's with spaces don't render

- [ ] use a nicer component for entering code, or perhaps make better use of the props available

## Quality of Life

- [x] automatically update usages of layout when a new version is published
    _PR https://github.com/holistic-web/toolbox/pull/109_
    _Doesn't seem like the [commits from workflows trigger new workflows](https://github.community/t5/GitHub-Actions/Github-actions-workflow-not-triggering-with-tag-push/td-p/39685), need to investigate._
    _Second PR https://github.com/holistic-web/toolbox/pull/112_
    _Event fires successfully but this still doesn't work... More investigation required._
    _Sorted - now deploys all tools from the same workflow that published the new layout version. 🎈_

**Comment by michaelfitzhavey** [comment]
@andrewlew1s This sounds great - I'm not sure about a couple of the above:

> Add socials buttons and link to / create social media for holistic toolbox? I.e. LinkedIn Org / link to git
    _I'm not sure about linking to github yet, I'm not sure how we'd handle other collaborators if we are looking to monetize soon. You couldcreate a linkedin if you wanted to and link that?_

> We could have a v minimal footer?
    _Maybe, let's do the other things you've linked and the things I've mentioned before adding that unless it makes a lot of design sense to?_

Otherwise that sounds good, I really like the search idea. I'd also like to do some ideas from [the roadmap](https://github.com/holistic-web/toolbox/tree/master/website#roadmap). Particularly:

- a little more text about what the toolbox is

- add consistency to tool picture and button sizes

- a contact us form, or perhaps just an email address, to report bugs or suggest changes

- mobile friendly

- audit the page with [google lighthouse](https://developers.google.com/web/tools/lighthouse) and make any suggested changes

**Comment by andrewlew1s** [comment]
> @andrewlew1s This sounds great - I'm not sure about a couple of the above:
> 
> > Add socials buttons and link to / create social media for holistic toolbox? I.e. LinkedIn Org / link to git
> > _I'm not sure about linking to github yet, I'm not sure how we'd handle other collaborators if we are looking to monetize soon. You couldcreate a linkedin if you wanted to and link that?_
> 
> > We could have a v minimal footer?
> > _Maybe, let's do the other things you've linked and the things I've mentioned before adding that unless it makes a lot of design sense to?_
> 
> Otherwise that sounds good, I really like the search idea. I'd also like to do some ideas from [the roadmap](https://github.com/holistic-web/toolbox/tree/master/website#roadmap). Particularly:
> 
> * a little more text about what the toolbox is
> * add consistency to tool picture and button sizes
> * a contact us form, or perhaps just an email address, to report bugs or suggest changes
> * mobile friendly
> * audit the page with [google lighthouse](https://developers.google.com/web/tools/lighthouse) and make any suggested changes

Integrated these ideas into initial comment

**Comment by michaelfitzhavey** [comment]
Good progress so far. As a two week review of this task we have:

**@andrewlew1s:**
- #103: adding a sentence to the main website

**Comment by michaelfitzhavey** [comment]
😱
